// Code generated by "stringer -type OperatorType -trimprefix=Op"; DO NOT EDIT.

package lox

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrOp-0]
	_ = x[OpAdd-1]
	_ = x[OpSubtract-2]
	_ = x[OpMultiply-3]
	_ = x[OpDivide-4]
	_ = x[OpEqualTo-5]
	_ = x[OpNotEqualTo-6]
	_ = x[OpLessThan-7]
	_ = x[OpLessThanOrEqualTo-8]
	_ = x[OpGreaterThan-9]
	_ = x[OpGreaterThanOrEqualTo-10]
}

const _OperatorType_name = "ErrOpAddSubtractMultiplyDivideEqualToNotEqualToLessThanLessThanOrEqualToGreaterThanGreaterThanOrEqualTo"

var _OperatorType_index = [...]uint8{0, 5, 8, 16, 24, 30, 37, 47, 55, 72, 83, 103}

func (i OperatorType) String() string {
	if i < 0 || i >= OperatorType(len(_OperatorType_index)-1) {
		return "OperatorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OperatorType_name[_OperatorType_index[i]:_OperatorType_index[i+1]]
}
