// Code generated by "stringer -type OperatorType -trimprefix=Op"; DO NOT EDIT.

package lox

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpNone-0]
	_ = x[OpPlus-1]
	_ = x[OpMinus-2]
	_ = x[OpMultiply-3]
	_ = x[OpDivide-4]
	_ = x[OpEquals-5]
	_ = x[OpEqualEquals-6]
	_ = x[OpNotEquals-7]
	_ = x[OpLess-8]
	_ = x[OpLessEquals-9]
	_ = x[OpGreater-10]
	_ = x[OpGreaterEquals-11]
}

const _OperatorType_name = "NonePlusMinusMultiplyDivideEqualsEqualEqualsNotEqualsLessLessEqualsGreaterGreaterEquals"

var _OperatorType_index = [...]uint8{0, 4, 8, 13, 21, 27, 33, 44, 53, 57, 67, 74, 87}

func (i OperatorType) String() string {
	if i < 0 || i >= OperatorType(len(_OperatorType_index)-1) {
		return "OperatorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OperatorType_name[_OperatorType_index[i]:_OperatorType_index[i+1]]
}
