// Code generated by "stringer -type TokenType"; DO NOT EDIT.

package lox

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[LeftParen-1]
	_ = x[RightParen-2]
	_ = x[LeftBrace-3]
	_ = x[RightBrace-4]
	_ = x[Comma-5]
	_ = x[Dot-6]
	_ = x[Minus-7]
	_ = x[Plus-8]
	_ = x[Semicolon-9]
	_ = x[Slash-10]
	_ = x[Star-11]
	_ = x[Bang-12]
	_ = x[BangEqual-13]
	_ = x[Equal-14]
	_ = x[EqualEqual-15]
	_ = x[Greater-16]
	_ = x[GreaterEqual-17]
	_ = x[Less-18]
	_ = x[LessEqual-19]
	_ = x[Identifier-20]
	_ = x[String-21]
	_ = x[Number-22]
	_ = x[And-23]
	_ = x[Class-24]
	_ = x[Else-25]
	_ = x[False-26]
	_ = x[Fun-27]
	_ = x[For-28]
	_ = x[If-29]
	_ = x[Nil-30]
	_ = x[Or-31]
	_ = x[Print-32]
	_ = x[Return-33]
	_ = x[Super-34]
	_ = x[This-35]
	_ = x[True-36]
	_ = x[Var-37]
	_ = x[While-38]
	_ = x[Comment-39]
	_ = x[EOF-40]
}

const _TokenType_name = "NoneLeftParenRightParenLeftBraceRightBraceCommaDotMinusPlusSemicolonSlashStarBangBangEqualEqualEqualEqualGreaterGreaterEqualLessLessEqualIdentifierStringNumberAndClassElseFalseFunForIfNilOrPrintReturnSuperThisTrueVarWhileCommentEOF"

var _TokenType_index = [...]uint8{0, 4, 13, 23, 32, 42, 47, 50, 55, 59, 68, 73, 77, 81, 90, 95, 105, 112, 124, 128, 137, 147, 153, 159, 162, 167, 171, 176, 179, 182, 184, 187, 189, 194, 200, 205, 209, 213, 216, 221, 228, 231}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
