// Code generated by "stringer -type Type -trimprefix=Type"; DO NOT EDIT.

package lox

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeAny-0]
	_ = x[TypeNil-1]
	_ = x[TypeNumeric-2]
	_ = x[TypeString-3]
	_ = x[TypeBoolean-4]
}

const _Type_name = "AnyNilNumericStringBoolean"

var _Type_index = [...]uint8{0, 3, 6, 13, 19, 26}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
